name: Semgrep Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Run Semgrep SAST only
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            semgrep/semgrep:1.92.0 semgrep scan \
            --config p/security-audit \
            --jobs 1 \
            --max-memory 3500 \
            --exclude node_modules \
            --exclude dist \
            --exclude build \
            --exclude .git \
            --sarif-output=/src/semgrep.sarif /src

      - name: Upload SARIF report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-report
          path: semgrep.sarif
          retention-days: 7

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
